// flow-typed signature: be5f6ba314663543524e92a7e209e71b
// flow-typed version: <<STUB>>/condense-newlines_v^0.2.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'condense-newlines'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'condense-newlines' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'condense-newlines/index' {
  declare module.exports: $Exports<'condense-newlines'>;
}
declare module 'condense-newlines/index.js' {
  declare module.exports: $Exports<'condense-newlines'>;
}
