// flow-typed signature: 68fb3f2710e74803b8ce0ef5f18a2327
// flow-typed version: <<STUB>>/dasherize_v^2.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dasherize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dasherize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dasherize/example/dash' {
  declare module.exports: any;
}

declare module 'dasherize/test/dash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dasherize/example/dash.js' {
  declare module.exports: $Exports<'dasherize/example/dash'>;
}
declare module 'dasherize/index' {
  declare module.exports: $Exports<'dasherize'>;
}
declare module 'dasherize/index.js' {
  declare module.exports: $Exports<'dasherize'>;
}
declare module 'dasherize/test/dash.js' {
  declare module.exports: $Exports<'dasherize/test/dash'>;
}
