// flow-typed signature: 4a710c3d31405292cb51ff6772377a66
// flow-typed version: <<STUB>>/html-tag_v^1.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-tag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-tag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'html-tag/index' {
  declare module.exports: $Exports<'html-tag'>;
}
declare module 'html-tag/index.js' {
  declare module.exports: $Exports<'html-tag'>;
}
