// flow-typed signature: 684ce2efbe44eeb60954d79ef56a53a9
// flow-typed version: <<STUB>>/mic-tap-format_v^1.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mic-tap-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mic-tap-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mic-tap-format/bin/index' {
  declare module.exports: any;
}

declare module 'mic-tap-format/dist/index' {
  declare module.exports: any;
}

declare module 'mic-tap-format/dist/lib/diff-strings' {
  declare module.exports: any;
}

declare module 'mic-tap-format/dist/lib/exit' {
  declare module.exports: any;
}

declare module 'mic-tap-format/dist/lib/failures' {
  declare module.exports: any;
}

declare module 'mic-tap-format/dist/lib/pad' {
  declare module.exports: any;
}

declare module 'mic-tap-format/dist/lib/parser' {
  declare module.exports: any;
}

declare module 'mic-tap-format/dist/lib/results' {
  declare module.exports: any;
}

declare module 'mic-tap-format/src/index' {
  declare module.exports: any;
}

declare module 'mic-tap-format/src/lib/diff-strings' {
  declare module.exports: any;
}

declare module 'mic-tap-format/src/lib/exit' {
  declare module.exports: any;
}

declare module 'mic-tap-format/src/lib/failures' {
  declare module.exports: any;
}

declare module 'mic-tap-format/src/lib/pad' {
  declare module.exports: any;
}

declare module 'mic-tap-format/src/lib/parser' {
  declare module.exports: any;
}

declare module 'mic-tap-format/src/lib/results' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mic-tap-format/bin/index.js' {
  declare module.exports: $Exports<'mic-tap-format/bin/index'>;
}
declare module 'mic-tap-format/dist/index.js' {
  declare module.exports: $Exports<'mic-tap-format/dist/index'>;
}
declare module 'mic-tap-format/dist/lib/diff-strings.js' {
  declare module.exports: $Exports<'mic-tap-format/dist/lib/diff-strings'>;
}
declare module 'mic-tap-format/dist/lib/exit.js' {
  declare module.exports: $Exports<'mic-tap-format/dist/lib/exit'>;
}
declare module 'mic-tap-format/dist/lib/failures.js' {
  declare module.exports: $Exports<'mic-tap-format/dist/lib/failures'>;
}
declare module 'mic-tap-format/dist/lib/pad.js' {
  declare module.exports: $Exports<'mic-tap-format/dist/lib/pad'>;
}
declare module 'mic-tap-format/dist/lib/parser.js' {
  declare module.exports: $Exports<'mic-tap-format/dist/lib/parser'>;
}
declare module 'mic-tap-format/dist/lib/results.js' {
  declare module.exports: $Exports<'mic-tap-format/dist/lib/results'>;
}
declare module 'mic-tap-format/src/index.js' {
  declare module.exports: $Exports<'mic-tap-format/src/index'>;
}
declare module 'mic-tap-format/src/lib/diff-strings.js' {
  declare module.exports: $Exports<'mic-tap-format/src/lib/diff-strings'>;
}
declare module 'mic-tap-format/src/lib/exit.js' {
  declare module.exports: $Exports<'mic-tap-format/src/lib/exit'>;
}
declare module 'mic-tap-format/src/lib/failures.js' {
  declare module.exports: $Exports<'mic-tap-format/src/lib/failures'>;
}
declare module 'mic-tap-format/src/lib/pad.js' {
  declare module.exports: $Exports<'mic-tap-format/src/lib/pad'>;
}
declare module 'mic-tap-format/src/lib/parser.js' {
  declare module.exports: $Exports<'mic-tap-format/src/lib/parser'>;
}
declare module 'mic-tap-format/src/lib/results.js' {
  declare module.exports: $Exports<'mic-tap-format/src/lib/results'>;
}
