// flow-typed signature: 0b78648a1b7d62c039430be6918c94ce
// flow-typed version: <<STUB>>/postcss-js_v^1.0.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-js/async' {
  declare module.exports: any;
}

declare module 'postcss-js/objectifier' {
  declare module.exports: any;
}

declare module 'postcss-js/parser' {
  declare module.exports: any;
}

declare module 'postcss-js/process-result' {
  declare module.exports: any;
}

declare module 'postcss-js/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-js/async.js' {
  declare module.exports: $Exports<'postcss-js/async'>;
}
declare module 'postcss-js/index' {
  declare module.exports: $Exports<'postcss-js'>;
}
declare module 'postcss-js/index.js' {
  declare module.exports: $Exports<'postcss-js'>;
}
declare module 'postcss-js/objectifier.js' {
  declare module.exports: $Exports<'postcss-js/objectifier'>;
}
declare module 'postcss-js/parser.js' {
  declare module.exports: $Exports<'postcss-js/parser'>;
}
declare module 'postcss-js/process-result.js' {
  declare module.exports: $Exports<'postcss-js/process-result'>;
}
declare module 'postcss-js/sync.js' {
  declare module.exports: $Exports<'postcss-js/sync'>;
}
