/* @flow */

// flow-typed signature: 017ac99e13cda4d61d866c5af494189e
// flow-typed version: <<STUB>>/to-css_v^1.2.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-css/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-css/src/index.js' {
  declare module.exports: $Exports<'to-css/src/index'>;
}
